### ISSUE TITLE
Unable to get sum of estimated time over multiple contexts when I group by context

### ISSUE THREAD

**Issue by sidazhang** [dbyler/omnifocus-scripts#2]
Unable to get sum of estimated time over multiple contexts when I group by context

![](https://www.evernote.com/l/ASFb5oPxCK5Mp6vbXVs5gAOsTgnBsmeUT1kB/image.png)

**Comment by sidazhang** [comment]
As additional info, when I select items within the same context, it works

![](https://www.evernote.com/l/ASGWatf86RJHJ7_n9guPxSqnXsN134kcH6IB/image.png)

**Comment by GandalfSaxe** [comment]
I have the same problem, just when you set "Group projects by: Due", and all the tasks in the view is placed under some top-level items "Today", "Within the next week" etc.

Meaning that you carefully have to de-select those special items after doing "Cmd+A" and cannot just run the script on everything, which would be more convenient.

**Comment by dbyler** [comment]
Hey @sidazhang and @GandalfSaxe, apologies for completely missing this thread. This issues should be fixed - but please let me know if you run into any issues with the latest version.
