### ISSUE TITLE
How to install scripts?

### ISSUE THREAD

**Issue by sdaitzman** [dbyler/omnifocus-scripts#3]
I am particularly interested in the one that gets total time estimated for a group of tasks. Thank you in advance for any help you can offer!

**Comment by dbyler** [comment]
Hi Sam, apologies for missing this. In OmniFocus, choose `Help` → `Open Scripts Folder`. This will open the folder that you can put the scripts in. Then you can add them to your toolbar with `View` → `Customize Toolbar`.

Alternatively, you can use a utility like FastScripts, LaunchBar, or Alfred to run scripts.
