### ISSUE TITLE
Compatibility with OmniFocus 3?

### ISSUE THREAD

**Issue by stephanschubert** [dbyler/omnifocus-scripts#5]
Thanks for the work—I used your scripts in OF2 for some time now.

But in OF3 I tried to run "Total Time" and it complained about `context` being undefined.

Any ideas/plans to update?

**Comment by dbyler** [comment]
Ah yes, thanks for the catch. Guess it says something about my recent OmniFocus usage that I haven't run into this bug since I started using the OmniFocus 3 beta months ago :) Fixed.
